version: '3.8'

services:
  app:
    build: .
    container_name: data-cleaner-pro
    ports:
      - "8000:8000"   # FastAPI API
      - "8501:8501"   # Streamlit UI
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
